notifications:
  email: false
git:
  quiet: true
  depth: 1
language: node_js
node_js: lts/*
install: true
addons:
  apt:
    packages:
      - bash
      - curl
      - sudo
      - lsof
before_install:
  - source <(curl -s https://raw.githubusercontent.com/daggerok/bash-functions/master/main.bash)
  - stop_any 80 8001 8002 8080 5432
script:
  - npm i
  - npm run build
  - npm start &
  - wait_for 1234
  - curl http://127.0.0.1:1234/
  - stop_any 1234
before_deploy:
  - npm run gh-pages
deploy:
  provider: pages
  skip-cleanup: true
  github-token: "$GITHUB_TOKEN"
  keep-history: true
  on:
    branch: master
  local-dir: dist
  target_branch: gh-pages
